### PR TITLE
AWS credential modify (use DefaultAWSCredentialsProviderChain)

### PR DESCRIPTION
**Pull request by Impressionist**

### CODE REVIEW

**Comment by Ashex** [comment]
What are the benefits of this change?

**Comment by Impressionist** [comment]
If you use AWSCredentialsProviderChain, Authentication can be done in various ways.
I think authentication with IAM role is safer.
This is a java docs related to the IAM role.
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html

**Comment by avdhoot** [comment]
@Ashex Can we merge this. We want use aws ec2 Instance profile credentials. insted adding key/secret in graylog.

**Comment by bernd** [comment]
This got implemented in #36.

**Pull request closed without merging**
